### ISSUE TITLE
Publishing hangs on New Repo creation

### ISSUE THREAD

**Issue by baldwindavid** [baldwindavid/github-for-mac-issues#1]
When publishing a new repository, the publishing button is hanging and prohibiting other actions to be performed.
### Steps performed
- clicked "Create New Repository"
- added repository
- added file locally
- committed locally
- clicked "Publish Branch"
- "Publishing..." button then hangs
- while this hangs, it seems to also disable the "Commit Changes" button for local additions
### How to fix
- restart the application

**Comment by baldwindavid** [comment]
1.0.2 fixes

**Comment by Simonforeveryoung** [comment]
I am having the same issue. I restarted the many times but when publishing the repo it will just hang. Please help !!!
