### ISSUE TITLE
Unknown error when discarding changes?

### ISSUE THREAD

**Issue by epetousis** [baldwindavid/github-for-mac-issues#18]
I can't commit because of this:
(
    0   GitHub                              0x0000000100096531 -[GHApplication presentError:] + 445
    1   GitHub                              0x000000010006de34 __42-[GHChangesViewController discardChanges:]_block_invoke_0 + 48
    2   libdispatch.dylib                   0x00007fff89a0690a _dispatch_call_block_and_release + 18
    3   libdispatch.dylib                   0x00007fff89a0877a _dispatch_main_queue_callback_4CF + 308
    4   CoreFoundation                      0x00007fff93ef3c0c __CFRunLoopRun + 1724
    5   CoreFoundation                      0x00007fff93ef3216 CFRunLoopRunSpecific + 230
    6   HIToolbox                           0x00007fff918944ff RunCurrentEventLoopInMode + 277
    7   HIToolbox                           0x00007fff9189bc21 ReceiveNextEventCommon + 355
    8   HIToolbox                           0x00007fff9189baae BlockUntilNextEventMatchingListInMode + 62
    9   AppKit                              0x00007fff8fad8191 _DPSNextEvent + 659
    10  AppKit                              0x00007fff8fad7a95 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    11  AppKit                              0x00007fff8fad43d6 -[NSApplication run] + 463
    12  AppKit                              0x00007fff8fd5252a NSApplicationMain + 867
    13  GitHub                              0x00000001000014e4 start + 52
)

**Comment by malpais** [comment]
Hi,

It happened to me as well. Any devs know what this means?

(
    0   GitHub                              0x0000000100096531 -[GHApplication presentError:] + 445
    1   libdispatch.dylib                   0x00007fff8f11c8ba _dispatch_call_block_and_release + 18
    2   libdispatch.dylib                   0x00007fff8f11e72a _dispatch_main_queue_callback_4CF + 308
    3   CoreFoundation                      0x00007fff8d74b4dc __CFRunLoopRun + 1724
    4   CoreFoundation                      0x00007fff8d74aae6 CFRunLoopRunSpecific + 230
    5   HIToolbox                           0x00007fff94cfe3d3 RunCurrentEventLoopInMode + 277
    6   HIToolbox                           0x00007fff94d0563d ReceiveNextEventCommon + 355
    7   HIToolbox                           0x00007fff94d054ca BlockUntilNextEventMatchingListInMode + 62
    8   AppKit                              0x00007fff934843f1 _DPSNextEvent + 659
    9   AppKit                              0x00007fff93483cf5 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    10  AppKit                              0x00007fff9348062d -[NSApplication run] + 470
    11  AppKit                              0x00007fff936ff80c NSApplicationMain + 867
    12  GitHub                              0x00000001000014e4 start + 52
    13  ???                                 0x0000000000000002 0x0 + 2
)
