### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by pablofierro** [baldwindavid/github-for-mac-issues#19]
Hello, I'm having issues while performing any action that communicates to github i.e: committing, sync, push, etc..
The loading screen is displayed forever, http://cl.ly/3k2I0m350p470f07211V

This is the console log I'm getting
http://cl.ly/0m1I3V2C002G1N3H3o0Q

What could it be ?

**Comment by pablofierro** [comment]
I've downloaded an older version of the app and got it to work, however since the app updates itself automatically the error comes up again after restarting the app.

**Comment by lipsumar** [comment]
I just installed latest version but can't even login. spinning thing spins forever, even with a wrong password. definitely a connection to github issue.

**Comment by lipsumar** [comment]
Never mind, probably an error on my computer. had also strange stuff on Chrome. restarted. everything works including login to github with Github for Mac. :)

**Comment by pablofierro** [comment]
I solved the issue by updating to os x lion, app works great now!
