### ISSUE TITLE
diff view is broken with active color settings

### ISSUE THREAD

**Issue by havvg** [baldwindavid/github-for-mac-issues#7]
The diff view is broken, if colors are activated by default.
The command line accepts "--no-color" option, the result of this CLI should be used.

The current result is: http://dl.dropbox.com/u/548684/Screen%20shot%202011-06-24%20at%2019.38.13.png
The expected view should be: http://dl.dropbox.com/u/548684/Screen%20shot%202011-06-24%20at%2019.45.10.png

**Comment by baldwindavid** [comment]
Hi havvg - Please note that you will still have to submit this issue to Github manually.  I just updated the [README](https://github.com/baldwindavid/github-for-mac-issues) to clarify a bit.  Thanks!

**Comment by havvg** [comment]
Thanks, done :)
